# Generated by Django 2.1.7 on 2019-02-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dia03app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
    ]
