# Generated by Django 2.1.7 on 2019-02-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dia03app', '0002_auto_20190227_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('ac', 'Ação'), ('av', 'Aventura'), ('fc', 'Ficção'), ('tr', 'Terror'), ('cm', 'Comédia'), ('dr', 'Drama'), ('ro', 'Romance')], default='ac', max_length=2)),
                ('sinopse', models.TextField()),
                ('lancamento', models.DateField()),
                ('duracao', models.PositiveIntegerField()),
                ('classificacao_indicativa', models.PositiveIntegerField()),
                ('cartaz', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='banda',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Banda',
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
